on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    if: github.repository_owner == 'arpabot'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@f3969c04a4ec81d7a9aa4010d84ae6a7602f86a7 # v4.1.1
        id: release-please
        with:
          config-file: .github/release-please/release-please-config.json
          manifest-file: .github/release-please/.release-please-manifest.json
          skip-github-pull-request:
            ${{ startsWith(github.event.head_commit.message, 'release:') &&
            github.event.head_commit.author.name == 'github-actions[bot]' }}
